### PR TITLE
Added new space theme with responsiveness and tailwindCSS.

### PR DESCRIPTION
**Pull request by Mohit-Aasirwal**
#3  new space theme with dynamic moon background and made with tailwindCSS library. Kindly consider it for merging on 1st October under hacktoberfest 2022.

### CODE REVIEW

**Review by Noevenzahn — CHANGES_REQUESTED** [review]
Hey, thanks for your PR!
node_modules shouldn't be committed in this case. Not only do they bloat the PR and make it hard to review it, they also aren't needed at all. Everyone can install the dependencies with `npm install` when needed. 
Your `.vscode` directory shouldn't be committed, either. I recommend adding a `.gitignore` file that includes both directories to solve this.

**Comment by MichaelBarney** [comment]
As [Noevenzahn](https://github.com/Noevenzahn) pointed out, please change the PR to not include .vscode and  node_modules.

**Comment by Mohit-Aasirwal** [comment]
I've added gitignore file.
please merge the new theme now.

**Comment by MichaelBarney** [comment]
Even though you added the gitignore, the files are still added to the commit. Please review the added files for the PR to be accepted.

**Comment by Mohit-Aasirwal** [comment]
OK! I think now it is implemented. You can merge now.
I enjoyed contributing to this  repo
Gracias!

**Comment by Mohit-Aasirwal** [comment]
please label this PR as hacktoberfest accepted.

**Pull request merged**
